// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq1SKK_My9dvlN6aORySou6_fDcCtJ0Ig',
    appId: '1:557432005946:web:a2fdf4ad599bd0a681dc03',
    messagingSenderId: '557432005946',
    projectId: 'five-of-us',
    authDomain: 'five-of-us.firebaseapp.com',
    storageBucket: 'five-of-us.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3b0_Y5qQRvSnqAQ3Kc8_CcUdlhAs6tQ',
    appId: '1:557432005946:android:c9f24a155f96d87b81dc03',
    messagingSenderId: '557432005946',
    projectId: 'five-of-us',
    storageBucket: 'five-of-us.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD_PgPaNeYiRLYy-EZtMsyimKj_ZnxF6c',
    appId: '1:557432005946:ios:cb0185a6034951eb81dc03',
    messagingSenderId: '557432005946',
    projectId: 'five-of-us',
    storageBucket: 'five-of-us.firebasestorage.app',
    iosBundleId: 'com.example.fiveOfUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD_PgPaNeYiRLYy-EZtMsyimKj_ZnxF6c',
    appId: '1:557432005946:ios:cb0185a6034951eb81dc03',
    messagingSenderId: '557432005946',
    projectId: 'five-of-us',
    storageBucket: 'five-of-us.firebasestorage.app',
    iosBundleId: 'com.example.fiveOfUs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq1SKK_My9dvlN6aORySou6_fDcCtJ0Ig',
    appId: '1:557432005946:web:4caa8abf7796529d81dc03',
    messagingSenderId: '557432005946',
    projectId: 'five-of-us',
    authDomain: 'five-of-us.firebaseapp.com',
    storageBucket: 'five-of-us.firebasestorage.app',
  );
}
